FROM cypress/included:13.15.0

WORKDIR /e2e

# Copy package files
COPY package*.json ./

# Install additional dependencies
RUN npm install

# Copy source code and config
COPY cypress/ ./cypress/
COPY cypress.config.ts ./
COPY tsconfig.json ./

# Set environment variables

# Default command
CMD ["npx", "cypress", "run"]
